language: csharp
solution: PbaTestMiniProject.sln
install:
  - nuget restore PbaTestMiniProject.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release PbaTestMiniProject.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./KOUBAKaTestProject/bin/Release/KOUBAKaTestProject.dll

notifications:
      email: false
